import Now from "../../component/now";
import "../../styles/styles.module.css";

export const metadata = {
  title: "For a meaningful day",
  description: "Generated by SeolDong",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div id="UserState">
          <Now />
          <div>튜토리얼</div>
          <div>로그인 / 회원가입</div>
        </div>
        <div id="ContentContainer">{children}</div>
      </body>
    </html>
  );
}
