import { customInitApp } from "../lib/firebase-admin-config";
import NavMenu from "../components/navMenu";
import "./globals.css";
import { auth } from '../lib/firebase-config';

export const metadata = {
  title: "For a meaningful day",
  description: "Generated by SeolDong",
};


export default async function RootLayout({ children }) {

  return (
    <html>
      <body className="h-screen w-screen">
        <NavMenu />
        <section className="h-full w-full">{children}</section>
      </body>
    </html>
  );
}
