import Link from 'next/link';
import CurrentTime from '../../component/currentTime';

export const metadata = {
  title: "For a meaningful day",
  description: "Generated by SeolDong",
};

export default function RootLayout({ children }) {

  const login = 0;

  return (
    <html>
      <body>
        <nav>
          <div><CurrentTime /></div>
          <div id="UserState">
            <div>
              <Link href={`/`}>guest</Link>
            </div>
            <div>
              <Link href={`/membership`}>로그인</Link>
            </div>
          </div>
        </nav>
        <section id="ContentContainer">{children}</section>
      </body>
    </html>
  );
}
