import Link from 'next/link';
import CurrentTime from '../../component/currentTime';
import HomePage from './page';
import DefaultMenu from '../../component/guest/defaultMenu';

export const metadata = {
  title: "For a meaningful day",
  description: "Generated by SeolDong",
};

export default function RootLayout({ children }) {

  return (
    <html>
      <body>

        <nav>
          <div><CurrentTime /></div>
          <div>
            <Link href={'/signIn'}>sign in</Link><br />
            <Link href={'/signUp'}>sign up</Link>
          </div>
        </nav>

        <section id="ContentContainer">
          <div>{children}</div>
        </section>

      </body>
    </html>
  );
}